In [ ]:
import numpy as np
my_array = np.array([0,1,2,3,4])
print(my_array)
print(type(my_array))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
array_A = np.array([1,2,3])
array_B = np.array([4,5,6])
print(array_A + array_B)

[5 7 9]


In [8]:
months_array = np.array(['Jan','Feb','Mar','April','May'])
print(months_array[3])

April


In [ ]:
array_a = np.array([1,2,3])
array_b = np.array([[1,2,3],[4,5,6]])
print(array_a)
print(array_b)
print(array_a.shape)
print(array_b.shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)
[0.   0.25 0.5  0.75 1.  ]


In [49]:
zeros = np.zeros((3,3))
print(f"Matrix filled with zeros:\n{zeros}\n")

ones = np.ones((2,3,4))
print(f"Two matrices filled with ones:\n{ones}\n")

identity = np.eye(3)
print(f"indentity matrix:\n{identity}\n")

range_arr = np.arange(10)
print(f"Range of values:\n{range_arr}\n")

three = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 matrix
print(f"3x3 matrix:\n{three}\n")
print(f"Shape of array:{three.shape}\n")

full = np.full((3,3),2)
print(f"3x3 matrix full of 2:\n{full}\n")

linespace = np.linspace(0,100,5)
print(f"Having different interval between the no.:\n{linespace}")

Matrix filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Two matrices filled with ones:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

indentity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Range of values:
[0 1 2 3 4 5 6 7 8 9]

3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array:(3, 3)

3x3 matrix full of 2:
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Having different interval between the no.:
[  0.  25.  50.  75. 100.]


In [61]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)
print(matrix[1,1])  # First method
print(matrix[2][1]) # Second method
print(matrix[0,1:3]) # print the row value
print(matrix[1:3,0]) # print the column value

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
80
[20 30]
[40 70]


In [64]:
value1 = matrix[1,1]
value2 = matrix[2,2]
linespace = np.linspace(value1,value2,5)
print(linespace)

[50. 60. 70. 80. 90.]


# Basic Arithmetic

In [68]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a*2)
print(a+10)
print(a-1)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[1 2 3 4]
[2 4 6 8]
[11 12 13 14]
[0 1 2 3]


# Broadcasting array of different dimensions


In [78]:
# vector + vector
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(f"vector + vector array:\n{a+b}\n")

# matrix + vector
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([10,20,30])
print(f"matrix + vector array:\n{matrix + vector}\n")

# matrix + col vector
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_vector = np.array([[10],[20],[30]])
print(f"matrix + col_vector array:\n{matrix + col_vector}\n")


vector + vector array:
[ 6  8 10 12]

matrix + vector array:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

matrix + col_vector array:
[[11 12 13]
 [24 25 26]
 [37 38 39]]



In [98]:
import pandas as pd

data = {

    'Name': ['Adwait','Yuvraj','Pratham'],
    'Age' : [19,19,20],
    'City': ['Palghar','Patna','Chandrapur']
}

df = pd.DataFrame(data)
print(df)
df.to_csv("data.csv",index=False)
df.to_json('data.json', indent=3)

      Name  Age        City
0   Adwait   19     Palghar
1   Yuvraj   19       Patna
2  Pratham   20  Chandrapur
